- inference_config: "configs/inference/inference.yaml"

  unet_path: "../../model/ImageConductor/unet.ckpt"
  image_controlnet_path: "../../model/ImageConductor/image_controlnet.ckpt"
  flow_controlnet_path: "../../model/ImageConductor/flow_controlnet.ckpt"

  image_controlnet_config: "configs/inference/image_condition.yaml"
  flow_controlnet_config: "configs/inference/flow_condition.yaml"


  # H: 256 
  # W: 384 
  H: 320 #256 
  W: 512 #384 
  L: 16
  seed: [10294865041322163136]
  steps: 25
  guidance_scale: 7.5

  controlnet_image_indexs: [0]
  controlnet_images:
    - "__asset__/images/object/rose-1.jpg"
  controlnet_trajs: "__asset__/trajs/object/rose-1.json"
  control_mode: "object"

  prompt:
    - "a red rose engulfed in flames."
  
  n_prompt:
    - "worst quality, low quality, letterboxed"
